# Generated by Django 3.1.4 on 2021-02-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
