# Generated by Django 3.1.4 on 2021-03-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_products_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='seller',
            field=models.CharField(default='Not-Specified', max_length=150),
        ),
    ]
